{
  "groups": [
    {
      "name": "general.rules",
      "rules": [
        {
          "alert": "TargetDown",
          "annotations": {
            "message": "{{ printf \"%.4g\" $value }}% of the {{ $labels.job }} targets are down."
          },
          "expr": "100 * (count(up == 0) BY (job, namespace, service) / count(up) BY (job, namespace, service)) > 10",
          "for": "10m",
          "labels": {
            "severity": "warning"
          }
        },
        {
          "alert": "BlackboxProbeFailure",
          "annotations": {
            "message": "Blackbox probe {{$labels.instance}} failed"
          },
          "expr": "probe_success == 0",
          "for": "2m",
          "labels": {
            "severity": "critical"
          }
        }
      ]
    },
    {
      "name": "extra.rules",
      "rules": [
        {
          "alert": "InactiveRAIDDisk",
          "annotations": {
            "message": "{{ $value }} RAID disk(s) on node {{ $labels.instance }} are inactive."
          },
          "expr": "node_md_disks{state=\"failed\"} > 0",
          "for": "10m",
          "labels": {
            "severity": "warning"
          }
        }
      ]
    }
  ]
}