apiVersion: 1
providers:
  - name: 'kubernetes'
    ordId: 1
    folder: 'Kubernetes'
    type: file
    options:
      path: /etc/grafana/dashboards/kubernetes
  - name: 'nodes'
    ordId: 1
    folder: 'Nodes'
    type: file
    options:
      path: /etc/grafana/dashboards/nodes
