apiVersion: 1
providers:
  - name: 'default'
    ordId: 1
    updateIntervalSeconds: 60 #how often Grafana will scan for changed dashboards
    folder: ''
    type: file
    options:
      path: /etc/grafana/dashboards
